import * as React from 'react';

import Page, { Content } from 'components/core/styled/Page';
import Row from 'components/core/styled/Row';
import Column from 'components/core/styled/Column';

const Dashboard = () => {
  return (
    <Page>
      <Content>
        <Row>
          <Column>
            <div>Dashboard</div>
            <div>Options</div>
            <div>Log out</div>
          </Column>

          <Column style={{ flex: 1 }}>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
            <div>Dashboard</div>
          </Column>
        </Row>
      </Content>
    </Page>
  );
};

export default Dashboard;
